spring:
  application:
    name: Product-Service
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Disable hibernate auto schema creation
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  # Makes console log output colourful
  output:
    ansi:
      enabled: ALWAYS
  lifecycle:
    timeout-per-shutdown-phase: 20s
  threads:
    virtual:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: "/product-service"
  shutdown: graceful
