INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE, STOCK_STATUS, STOCK_COUNT) VALUES (1, 'PRODUCT 1', 2000, 'AVAILABLE', 100);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE, STOCK_STATUS, STOCK_COUNT) VALUES (2, 'PRODUCT 2', 500.50, 'AVAILABLE', 47);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE, STOCK_STATUS, STOCK_COUNT) VALUES (3, 'PRODUCT 3', 140.56, 'OUT_OF_STOCK', 0);