INSERT INTO products (NAME, PRICE, STOCK_STATUS, STOCK_COUNT)
VALUES ('PRODUCT 1', 2000, 'AVAILABLE', 100);
INSERT INTO products (NAME, PRICE, STOCK_STATUS, STOCK_COUNT)
VALUES ('PRODUCT 2', 500.50, 'AVAILABLE', 47);
INSERT INTO products (NAME, PRICE, STOCK_STATUS, STOCK_COUNT)
VALUES ('PRODUCT 3', 140.56, 'OUT_OF_STOCK', 0);