INSERT INTO products (PRODUCT_ID, NAME, PRICE, STOCK_STATUS, STOCK_COUNT)
VALUES (NEXTVAL('product_id_seq'), 'PRODUCT 1', 2000, 'AVAILABLE', 100);
INSERT INTO products (PRODUCT_ID, NAME, PRICE, STOCK_STATUS, STOCK_COUNT)
VALUES (NEXTVAL('product_id_seq'), 'PRODUCT 2', 500.50, 'AVAILABLE', 47);
INSERT INTO products (PRODUCT_ID, NAME, PRICE, STOCK_STATUS, STOCK_COUNT)
VALUES (NEXTVAL('product_id_seq'), 'PRODUCT 3', 140.56, 'OUT_OF_STOCK', 0);